name: My Render Deployment

on:
  push: 
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  render_deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}